[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/UnBan.list"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/direct.list"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/blacklist.list"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanAD.list"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanProgramAD.list"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyPrivacy.list"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyList.list"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash.list"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyListChina.list"

[[rulesets]]
group = "ğŸ® Switch"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/switch.list"

[[rulesets]]
group = "ğŸ’° PayPal"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/paypal.list"

[[rulesets]]
group = "ğŸ’¬ OpenAI"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/OpenAi.list"

[[rulesets]]
group = "ğŸ“½ YouTube"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸ—½ Proxies"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/duplingo.list"

[[rulesets]]
group = "ğŸ‘‘ Emby"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/emby.list"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/myrules.list"

[[rulesets]]
group = "ğŸ‡ºğŸ‡¸ Cloudcone"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/special.list"

[[rulesets]]
group = "â± Speedtest"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/speedtest.list"

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Google.list"

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/GoogleFCM.list"

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/GoogleCN.list"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Bing.list"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/OneDrive.list"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Microsoft.list"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Apple.list"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Telegram.list"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/SteamCN.list"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Epic.list"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Steam.list"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Nintendo.list"

[[rulesets]]
group = "ğŸ¥ NETFLIX"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Netflix.list"

[[rulesets]]
group = "ğŸ—½ Proxies"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyGFWlist.list"

[[rulesets]]
group = "DIRECT"
# group = "ğŸ¯ Domestic"
ruleset = "[]GEOIP,CN,no-resolve"

[[rulesets]]
group = "ğŸŸ Slipped"
ruleset = "[]FINAL"
