[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.list"

[[rulesets]]
group = "DIRECT"
# group = "ğŸ¯ Domestic"
ruleset = "[]GEOIP,CN,no-resolve"

[[rulesets]]
group = "ğŸŸ Slipped"
ruleset = "[]FINAL"
