[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/UnBan.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanAD.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanProgramAD.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyList.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyListChina.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyPrivacy.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/direct.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/blacklist.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ® Switch"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/switch.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ—½ Proxies"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/duplingo.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ‘‘ Emby"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/emby.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/myrules.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ‡ºğŸ‡¸ Cloudcone"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/special.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "â± Speedtest"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/speedtest.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ’° PayPal"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/paypal.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ“½ YouTube"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/YouTube.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Google.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/GoogleFCM.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/GoogleCN.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Bing.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/OneDrive.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Microsoft.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Apple.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Telegram.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ’¬ OpenAI"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/OpenAi.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/SteamCN.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Epic.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Steam.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Nintendo.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ¥ NETFLIX"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Netflix.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "ğŸ—½ Proxies"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyGFWlist.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaDomain.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaIp.yaml"
type = "clash-classic"
interval = 86400

[[rulesets]]
group = "DIRECT"
# group = "DIRECT"
ruleset = "[]GEOIP,CN,no-resolve"

[[rulesets]]
group = "ğŸŸ Slipped"
ruleset = "[]FINAL"
