[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/refs/heads/master/Clash/Providers/Providers/UnBan.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/direct.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/blacklist.yaml"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanAD.yaml"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanProgramAD.yaml"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyPrivacy.yaml"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyList.yaml"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"

[[rulesets]]
group = "ğŸ›‘ Global_interception"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanEasyListChina.yaml"

[[rulesets]]
group = "ğŸ® Switch"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/switch.yaml"

[[rulesets]]
group = "ğŸ’° PayPal"
ruleset = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/paypal.yaml"

[[rulesets]]
group = "ğŸ’¬ OpenAI"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/OpenAi.yaml"

[[rulesets]]
group = "ğŸ“½ YouTube"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/YouTube.yaml"

[[rulesets]]
group = "ğŸ—½ Proxies"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/duplingo.yaml"

[[rulesets]]
group = "ğŸ‘‘ Emby"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/emby.yaml"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/myrules.yaml"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/OneDrive.yaml"

[[rulesets]]
group = "ğŸ‡¸ğŸ‡¬ VKVM_SG"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/special.yaml"

[[rulesets]]
group = "â± Speedtest"
ruleset = "https://raw.githubusercontent.com/vkingw/AutoBuild-OpenWrt/v23.05/rule-providers/speedtest.yaml"

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Google.yaml"

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/GoogleFCM.yaml"

[[rulesets]]
group = "âš¡ Google"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/GoogleCN.yaml"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/SteamCN.yaml"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Bing.yaml"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/OneDrive.yaml"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Microsoft.yaml"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Apple.yaml"

[[rulesets]]
group = "ï£¿ & â“‚ï¸"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Telegram.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/NetEaseMusic.yaml"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Epic.yaml"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Origin.yaml"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Sony.yaml"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Steam.yaml"

[[rulesets]]
group = "ğŸ® Game"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Nintendo.yaml"

[[rulesets]]
group = "ğŸ¥ NETFLIX"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Netflix.yaml"

[[rulesets]]
group = "ğŸ—½ Proxies"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Bahamut.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/BilibiliHMT.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Bilibili.yaml"

[[rulesets]]
group = "ğŸŒ Domestic_media"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaMedia.yaml"

# [[rulesets]]
# group = "ğŸŒ Foreign_media"
# ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyMedia.yaml"

[[rulesets]]
group = "ğŸ—½ Proxies"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ProxyGFWlist.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaIp.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaDomain.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/ChinaCompanyIp.yaml"

[[rulesets]]
group = "ğŸ¯ Domestic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Download.yaml"

[[rulesets]]
group = "DIRECT"
# group = "ğŸ¯ Domestic"
ruleset = "[]GEOIP,CN,no-resolve"

[[rulesets]]
group = "ğŸŸ Slipped"
ruleset = "[]FINAL"
