[[custom_groups]]
name = "ğŸ—½ Proxies"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡°ğŸ‡· KR",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
    "[]ğŸŒˆ United Nations",
    "[]ğŸŒˆ CF",
]

[[custom_groups]]
name = "ğŸ“½ YouTube"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
    "[]ğŸŒˆ United Nations",
    "[]ğŸŒˆ CF",
]

[[custom_groups]]
name = "âš¡ Google"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
    "[]ğŸŒˆ United Nations",
    "[]ğŸŒˆ CF",
]

[[custom_groups]]
name = "ğŸ’¬ OpenAI"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
    "[]ğŸŒˆ CF",
]

[[custom_groups]]
name = "ï£¿ & â“‚ï¸"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
    "[]ğŸŒˆ CF",
]

[[custom_groups]]
name = "ğŸ‘‘ Emby"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
    "[]ğŸŒˆ CF",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸ® Switch"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
    "[]ğŸŒˆ CF",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸ® Game"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
    "[]ğŸŒˆ CF",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸŒ Foreign_media"
type = "select"
rule = ["æ¸¯|å°|ç¾|æ–°åŠ å¡|æ—¥"]
# rule = [
#     "[]ğŸ‡ºğŸ‡¸ US",
#     "[]ğŸ‡¹ğŸ‡¼ TW",
#     "[]ğŸ‡­ğŸ‡° HK",
#     "[]ğŸ‡¸ğŸ‡¬ SG",
#     "[]ğŸ‡¯ğŸ‡µ JP",
    # "[]ğŸ‡ºğŸ‡¸ DMIT",
    # "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    # "[]ğŸ‡ºğŸ‡¸ NFW",
    # "[]ğŸ‡ºğŸ‡¸ NFW Balance",
#     "[]ğŸŒˆ CF",
#     "[]DIRECT",
# ]

[[custom_groups]]
name = "ğŸŒ Domestic_media"
type = "select"
rule = ["[]DIRECT", "[]ğŸ‡¹ğŸ‡¼ TW", "[]ğŸ‡­ğŸ‡° HK"]

[[custom_groups]]
name = "ğŸ¥ NETFLIX"
type = "select"
rule = ["æ¸¯|å°|ç¾|æ–°åŠ å¡|æ—¥"]
# rule = ["[]ğŸ‡ºğŸ‡¸ US", "[]ğŸ‡¹ğŸ‡¼ TW", "[]ğŸ‡­ğŸ‡° HK", "[]ğŸ‡¸ğŸ‡¬ SG", "[]ğŸ‡¯ğŸ‡µ JP", "[]ğŸ‡ºğŸ‡¸ DMIT"]

[[custom_groups]]
name = "ğŸ’° PayPal"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ DMIT",
    "[]ğŸ‡ºğŸ‡¸ DMIT Balance",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸ‡ºğŸ‡¸ NFW Balance",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone",
    "[]ğŸ‡ºğŸ‡¸ Cloudcone Balance",
    "[]ğŸ‡ºğŸ‡¸ GPT",
    "[]ğŸ‡ºğŸ‡¸ GPT Balance",
    "[]ğŸ‡¯ğŸ‡µ YX",
    "[]ğŸ‡¯ğŸ‡µ YX Balance",
]

[[custom_groups]]
name = "â± Speedtest"
type = "select"
rule = [".*", "[]DIRECT"]
use = ["nfw_1", "nfw_2", "dmit_1", "dmit_2", "cf"]

[[custom_groups]]
name = "ğŸ›‘ Global_interception"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ¯ Domestic"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ Slipped"
type = "select"
rule = ["[]ğŸ—½ Proxies", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ US"
type = "select"
rule = [
    "(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)",
]
# lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ DMIT"
type = "select"
use = ["dmit"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ DMIT Balance"
type = "load-balance"
use = ["dmit"]
# strategy = "round-robin"
strategy = "consistent-hashing"
url = "https://www.gstatic.com/generate_204"
interval = 300
# lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ NFW"
type = "select"
use = ["nfw"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ NFW Balance"
type = "load-balance"
use = ["nfw"]
# strategy = "round-robin"
strategy = "consistent-hashing"
url = "https://www.gstatic.com/generate_204"
interval = 300
# lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ Cloudcone"
type = "select"
use = ["cc"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ Cloudcone Balance"
type = "load-balance"
use = ["cc"]
# strategy = "round-robin"
strategy = "consistent-hashing"
url = "https://www.gstatic.com/generate_204"
interval = 300
# lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ GPT"
type = "select"
use = ["cc"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ GPT Balance"
type = "load-balance"
use = ["gpt"]
# strategy = "round-robin"
strategy = "consistent-hashing"
url = "https://www.gstatic.com/generate_204"
interval = 300
# lazy = true

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ YX"
type = "select"
use = ["yx"]
# lazy = true

[[custom_groups]]
name = ""ğŸ‡¯ğŸ‡µ YX Balance"
type = "load-balance"
use = ["yx"]
# strategy = "round-robin"
strategy = "consistent-hashing"
url = "https://www.gstatic.com/generate_204"
interval = 300
# lazy = true

[[custom_groups]]
name = "ğŸŒˆ CF"
type = "select"
use = ["cf"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ TW"
type = "select"
rule = ["å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° HK"
type = "select"
rule = ["æ¸¯|HK|hk|Hong Kong|HongKong|hongkong"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ SG"
type = "select"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ JP"
type = "select"
rule = ["æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan"]
# lazy = true

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· KR"
type = "select"
rule = ["KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“"]
# lazy = true

[[custom_groups]]
name = "ğŸŒˆ United Nations"
type = "select"
rule = [
    "ä¿„ç½—æ–¯.*",
    "åŠ æ‹¿å¤§.*",
    "å°åº¦.*",
    "åœŸè€³å…¶.*",
    "å¾·å›½.*",
    "æ³•å›½.*",
    "æ¾³å¤§åˆ©äºš.*",
    "çˆ±å°”å…°.*",
    "é©¬æ¥è¥¿äºš.*",
    "è‹±å›½.*",
    "è²å¾‹å®¾.*",
    "é˜¿æ ¹å»·.*",
    "åº”æ€¥èŠ‚ç‚¹.*",
    "å·´åŸºæ–¯å¦.*",
    "æ³°å›½.*",
    "è¿ªæ‹œ.*",
    "DE-.*",
    "UK.*",
]
# lazy = true
