[[custom_groups]]
name = "ğŸ—½ Proxies"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡°ğŸ‡· KR",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸŒˆ United Nations",
    "[]ğŸŒˆ CF",
]

[[custom_groups]]
name = "ğŸ“½ YouTube"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸŒˆ United Nations",
    "[]ğŸŒˆ CF",
]

[[custom_groups]]
name = "âš¡ Google"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸŒˆ United Nations",
    "[]ğŸŒˆ CF",
]

[[custom_groups]]
name = "ğŸ’¬ OpenAI"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
]

[[custom_groups]]
name = "ğŸ‘‘ Emby"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸŒˆ CF",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸ® Switch"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸŒˆ CF",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸ® Game"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸŒˆ CF",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸŒ Foreign media"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
    "[]ğŸŒˆ CF",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸŒ Domestic media"
type = "select"
rule = ["[]DIRECT", "[]ğŸ‡¹ğŸ‡¼ TW", "[]ğŸ‡­ğŸ‡° HK"]

[[custom_groups]]
name = "ğŸ¥ NETFLIX"
type = "select"
rule = ["[]ğŸ‡ºğŸ‡¸ US", "[]ğŸ‡¹ğŸ‡¼ TW", "[]ğŸ‡­ğŸ‡° HK", "[]ğŸ‡¸ğŸ‡¬ SG", "[]ğŸ‡¯ğŸ‡µ JP"]

[[custom_groups]]
name = "ğŸ’° PayPal"
type = "select"
rule = [
    "[]ğŸ‡ºğŸ‡¸ US",
    "[]ğŸ‡¹ğŸ‡¼ TW",
    "[]ğŸ‡­ğŸ‡° HK",
    "[]ğŸ‡¸ğŸ‡¬ SG",
    "[]ğŸ‡¯ğŸ‡µ JP",
    "[]ğŸ‡ºğŸ‡¸ NEW",
    "[]ğŸ‡ºğŸ‡¸ NFW",
]

[[custom_groups]]
name = "â± Speedtest"
type = "select"
rule = [".*", "[]DIRECT"]
use = ["new_1", "new_2", "nfw_1", "nfw_2", "cf"]

[[custom_groups]]
name = "ğŸ›‘ Global interception"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ¯ Domestic"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ Slipped"
type = "select"
rule = ["[]ğŸ—½ Proxies", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ US"
type = "select"
rule = [
    "(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)",
]
lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ NEW"
type = "select"
use = ["new_1", "new_2"]
lazy = true

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ NFW"
type = "select"
use = ["nfw_1", "nfw_2"]
lazy = true

[[custom_groups]]
name = "ğŸŒˆ CF"
type = "select"
use = ["cf"]
lazy = true

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ TW"
type = "select"
rule = ["å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan"]
lazy = true

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° HK"
type = "select"
rule = ["æ¸¯|HK|hk|Hong Kong|HongKong|hongkong"]
lazy = true

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ SG"
type = "select"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
lazy = true

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ JP"
type = "select"
rule = ["æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan"]
lazy = true

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· KR"
type = "select"
rule = ["KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“"]
lazy = true

[[custom_groups]]
name = "ğŸŒˆ United Nations"
type = "select"
rule = [
    "ä¿„ç½—æ–¯.*",
    "åŠ æ‹¿å¤§.*",
    "å°åº¦.*",
    "åœŸè€³å…¶.*",
    "å¾·å›½.*",
    "æ³•å›½.*",
    "æ¾³å¤§åˆ©äºš.*",
    "çˆ±å°”å…°.*",
    "é©¬æ¥è¥¿äºš.*",
    "è‹±å›½.*",
    "è²å¾‹å®¾.*",
    "é˜¿æ ¹å»·.*",
    "åº”æ€¥èŠ‚ç‚¹.*",
    "å·´åŸºæ–¯å¦.*",
    "æ³°å›½.*",
    "è¿ªæ‹œ.*",
    "DE-.*",
    "UK.*",
]
lazy = true
